services:
  vault:
    image: hashicorp/vault:1.16
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-root-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
  vault-seed:
    image: curlimages/curl:8.7.1
    depends_on: [vault]
    command: >
      sh -c "
      until curl -sf http://vault:8200/v1/sys/health >/dev/null; do sleep 1; done;
      curl -s -H 'X-Vault-Token: dev-root-token' -H 'Content-Type: application/json'
           -d '{\"data\":{\"POSTGRES_PASSWORD\":\"changeme\"}}'
           http://vault:8200/v1/secret/data/db-creds && echo 'Seeded Vault';
      "
    restart: "no"
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    image: stack-1-fastapi:dev   # optional but nice to name it
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: appdb
      DB_USER: appuser
      # (leave DB_PASSWORD out once Vault works)
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: dev-root-token
      VAULT_DB_SECRET_PATH: db-creds
      WATCHFILES_FORCE_POLLING: "true"
    volumes:
      - ./app:/app/app                   # <-- bind mount your code
    command: >
      python -m uvicorn app.main:app
      --host 0.0.0.0 --port 8000 --reload
    depends_on: [db, vault]
    ports:
      - "8000:8000"
volumes:
  pgdata:              # host:container
    # If you had a .env file, Compose auto-loads it in this directory
