services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    image: stack-1-fastapi:dev   # optional but nice to name it
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: changeme
      WATCHFILES_FORCE_POLLING: "true"
    volumes:
      - ./app:/app/app                   # <-- bind mount your code
    command: >
      python -m uvicorn app.main:app
      --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  pgdata:              # host:container
    # If you had a .env file, Compose auto-loads it in this directory
