apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: stack1
spec:
  replicas: 1
  selector:
    matchLabels: { app: vault }
  template:
    metadata:
      labels: { app: vault }
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.16
          args:
            - "server"
            - "-dev"
            - "-dev-root-token-id=dev-root-token"
            - "-dev-listen-address=0.0.0.0:8200"
          ports:
            - containerPort: 8200
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 2
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: stack1
spec:
  selector: { app: vault }
  ports:
    - name: http
      port: 8200
      targetPort: 8200
  type: ClusterIP
